kind: List
apiVersion: v1
items:

# describe db pvc
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: xycloud-ims-db-pvc
  spec:
    storageClassName: nfs-storage
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi

# describe db replicaset      
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: xycloud-ims-db-rs
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: xycloud-ims-db
    template:
      metadata:
        labels:
          app: xycloud-ims-db
      spec:
        containers:
        - name: xycloud-ims-db
          image: postgres
          env:
          - name: POSTGRES_DB
            value: "api_server_dev"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          volumeMounts:
          - name: db-volume
            mountPath: "/var/lib/postgresql/data"
        volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: xycloud-ims-db-pvc
            
# describe db service
- apiVersion: v1
  kind: Service
  metadata:
    name: xycloud-ims-db-srv
  spec:
    ports:
    - nodePort: 30010
      port: 5432
      targetPort: 5432
    selector:
      app: xycloud-ims-db
    type: NodePort
    
 # describe api server pvc
 - apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: xycloud-ims-api-pvc
  spec:
    storageClassName: nfs-storage
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
        
# describe api replicaset      
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: xycloud-ims-api-rs
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: xycloud-ims-api
    template:
      metadata:
        labels:
          app: xycloud-ims-api
      spec:
        containers:
        - name: xycloud-ims-api
          image: elixir:latest
          env:
            - name: HEX_MIRROR
              value: https://hexpm.upyun.com 
            - name: HEX_CDN
              value: https://hexpm.upyun.com
          workingDir: /app/xycloud-ims/api_server
          command: ["/bin/sh", "-c"]
          args: ["mix local.hex --force; mix archive.install --force hex phx_new 1.4.2; mix local.rebar --force; mix ecto.migrate; mix phx.server"]
          
          volumeMounts:
          - name: code-volume
            mountPath: /app"
          - name: file-volume
            mountPath: /app/xycloud-ims/api_server/priv/static/files
        volumes:
        - name: code-volume
          gitRepo:
            repository: https://github.com/threemonoliths/xycloud-ims.git
            revision: master
            directory: .
        - name: file-volume
          persistentVolumeClaim:
            claimName: xycloud-ims-api-pvc

            
# describe api service
- apiVersion: v1
  kind: Service
  metadata:
    name: xycloud-ims-api-srv
  spec:
    ports:
    - nodePort: 30011
      port: 4000
      targetPort: 4000
    selector:
      app: xycloud-ims-api
    type: NodePort
    
# describe web replicaset
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: xycloud-ims-web-rs
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: xycloud-ims-web
    template:
      metadata:
        labels:
          app: xycloud-ims-web
      spec:
        containers:
        - name: xycloud-ims-web
          image: 172.27.39.165:5000/xycloud-ims-web:v1

# describe web service
- apiVersion: v1
  kind: Service
  metadata:
    name: xycloud-ims-web-srv
  spec:
    ports:
    - nodePort: 30012
      port: 4200
      targetPort: 4200
    selector:
      app: xycloud-ims-web
    type: NodePort
    
          